-- Add COMP_PERSON_CODE and REGIST_CODE columns to companies_Member table
ALTER TABLE companies_Member 
ADD COLUMN COMP_PERSON_CODE varchar(100) AFTER MEMBER_CODE,
ADD COLUMN REGIST_CODE varchar(100) AFTER COMP_PERSON_CODE;
