-- Create companies_Member table
CREATE TABLE IF NOT EXISTS companies_Member (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  company_name VARCHAR(255) NOT NULL,
  company_type VARCHAR(100),
  registration_number VARCHAR(50),
  tax_id VARCHAR(50),
  address TEXT,
  province VARCHAR(100),
  postal_code VARCHAR(10),
  phone VARCHAR(20),
  website VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create documents_Member table
CREATE TABLE IF NOT EXISTS documents_Member (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  document_type ENUM('company_registration', 'tax_registration', 'other') NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create OTP verification table
CREATE TABLE IF NOT EXISTS otp_verification (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  phone VARCHAR(20) NOT NULL,
  otp_code VARCHAR(6) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP,
  used TINYINT(1) DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Create provinces table for autocomplete
CREATE TABLE IF NOT EXISTS provinces (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name_th VARCHAR(100) NOT NULL,
  name_en VARCHAR(100)
);

-- Insert Thai provinces data
INSERT INTO provinces (name_th, name_en) VALUES
('กรุงเทพมหานคร', 'Bangkok'),
('กระบี่', 'Krabi'),
('กาญจนบุรี', 'Kanchanaburi'),
('กาฬสินธุ์', 'Kalasin'),
('กำแพงเพชร', 'Kamphaeng Phet'),
('ขอนแก่น', 'Khon Kaen'),
('จันทบุรี', 'Chanthaburi'),
('ฉะเชิงเทรา', 'Chachoengsao'),
('ชลบุรี', 'Chonburi'),
('ชัยนาท', 'Chai Nat'),
('ชัยภูมิ', 'Chaiyaphum'),
('ชุมพร', 'Chumphon'),
('เชียงราย', 'Chiang Rai'),
('เชียงใหม่', 'Chiang Mai'),
('ตรัง', 'Trang'),
('ตราด', 'Trat'),
('ตาก', 'Tak'),
('นครนายก', 'Nakhon Nayok'),
('นครปฐม', 'Nakhon Pathom'),
('นครพนม', 'Nakhon Phanom'),
('นครราชสีมา', 'Nakhon Ratchasima'),
('นครศรีธรรมราช', 'Nakhon Si Thammarat'),
('นครสวรรค์', 'Nakhon Sawan'),
('นนทบุรี', 'Nonthaburi'),
('นราธิวาส', 'Narathiwat'),
('น่าน', 'Nan'),
('บึงกาฬ', 'Bueng Kan'),
('บุรีรัมย์', 'Buriram'),
('ปทุมธานี', 'Pathum Thani'),
('ประจวบคีรีขันธ์', 'Prachuap Khiri Khan'),
('ปราจีนบุรี', 'Prachinburi'),
('ปัตตานี', 'Pattani'),
('พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya'),
('พะเยา', 'Phayao'),
('พังงา', 'Phang Nga'),
('พัทลุง', 'Phatthalung'),
('พิจิตร', 'Phichit'),
('พิษณุโลก', 'Phitsanulok'),
('เพชรบุรี', 'Phetchaburi'),
('เพชรบูรณ์', 'Phetchabun'),
('แพร่', 'Phrae'),
('ภูเก็ต', 'Phuket'),
('มหาสารคาม', 'Maha Sarakham'),
('มุกดาหาร', 'Mukdahan'),
('แม่ฮ่องสอน', 'Mae Hong Son'),
('ยโสธร', 'Yasothon'),
('ยะลา', 'Yala'),
('ร้อยเอ็ด', 'Roi Et'),
('ระนอง', 'Ranong'),
('ระยอง', 'Rayong'),
('ราชบุรี', 'Ratchaburi'),
('ลพบุรี', 'Lopburi'),
('ลำปาง', 'Lampang'),
('ลำพูน', 'Lamphun'),
('เลย', 'Loei'),
('ศรีสะเกษ', 'Si Sa Ket'),
('สกลนคร', 'Sakon Nakhon'),
('สงขลา', 'Songkhla'),
('สตูล', 'Satun'),
('สมุทรปราการ', 'Samut Prakan'),
('สมุทรสงคราม', 'Samut Songkhram'),
('สมุทรสาคร', 'Samut Sakhon'),
('สระแก้ว', 'Sa Kaeo'),
('สระบุรี', 'Saraburi'),
('สิงห์บุรี', 'Sing Buri'),
('สุโขทัย', 'Sukhothai'),
('สุพรรณบุรี', 'Suphan Buri'),
('สุราษฎร์ธานี', 'Surat Thani'),
('สุรินทร์', 'Surin'),
('หนองคาย', 'Nong Khai'),
('หนองบัวลำภู', 'Nong Bua Lamphu'),
('อ่างทอง', 'Ang Thong'),
('อำนาจเจริญ', 'Amnat Charoen'),
('อุดรธานี', 'Udon Thani'),
('อุตรดิตถ์', 'Uttaradit'),
('อุทัยธานี', 'Uthai Thani'),
('อุบลราชธานี', 'Ubon Ratchathani');
